

const devs =[
    {
       id         : 1,
       name       : 'Joy Sarker',
       age        : 27,
       gender     : 'Male',
       skill      : 'MERN',
       income     : 500,
       location   :'Mirpur',
    },
    {
        id         : 2,
        name       : 'Asrful Sir',
        age        : 35,
        gender     : 'Male',
        skill      : 'MERN',
        income     : 1000,
        location   :'Mirpur',
     },
     {
        id         : 3,
        name       : 'Jillur Rhaman',
        age        : 30,
        gender     : 'Male',
        skill      : 'Wordpress',
        income     : 700,
        location   :'Uttara',
     },
     {
        id         : 4,
        name       : 'Md.Aktrul Islam',
        age        : 23,
        gender     : 'Male',
        skill      : 'Wordpress',
        income     : 400,
        location   :'Uttara',
     },
     {
        id         : 5,
        name       : 'Palash',
        age        : 40,
        gender     : 'Male',
        skill      : 'PHP',
        income     : 230,
        location   :'Banani',
     },
     {
        id         : 6,
        name       : 'Apu das',
        age        : 27,
        gender     : 'Male',
        skill      : 'PHP',
        income     : 500,
        location   :'Banani',
     },
     {
        id         : 7,
        name       : 'Rohit shatti',
        age        :14,
        gender     : 'Male',
        skill      : 'Java',
        income     : 600,
        location   :'Gulshan',
     },
     {
        id         : 8,
        name       : 'Mhamuda Aktar',
        age        : 27,
        gender     : 'Female',
        skill      : 'Java',
        income     : 500,
        location   :'Gulshan',
     },
     {
        id         : 9,
        name       : 'Joya Sarker',
        age        : 24,
        gender     : 'Female',
        skill      : 'Payton',
        income     : 700,
        location   :'Badda',
     },
     {
        id         : 10,
        name       : 'MD.Nur Islam',
        age        : 27,
        gender     : 'Male',
        skill      : 'Payton',
        income     : 900,
        location   :'Badda',
     },
];